# Generated by Django 5.0.7 on 2024-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Satyjy', 'Satyjy'), ('Alyjy', 'Alyjy')], max_length=50, null=True),
        ),
    ]
