# Generated by Django 5.0.7 on 2024-08-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finish_time',
            field=models.TimeField(blank=True, default='23:00', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
