# Generated by Django 5.0.7 on 2024-08-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_finish_time_profile_profile_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='finish_time',
            field=models.TimeField(blank=True, default='22:00', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(blank=True, default='06:00', null=True),
        ),
    ]
