# Generated by Django 5.0.7 on 2024-09-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Satyjy', ' Men Satyjy'), ('Alyjy', 'Men Alyjy')], max_length=50, null=True),
        ),
    ]
