# Generated by Django 5.0.7 on 2024-09-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Satyjy', 'Satyjy'), ('Alyjy', 'Alyjy')], max_length=50, null=True),
        ),
    ]
